services:
  db:
    image: postgres:17-alpine
    container_name: blog_db_con
    restart: always
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: blog_admin
      POSTGRES_PASSWORD: blog_password
    ports:
      - "5432:5432"
    volumes:
      - blog_db:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:latest
    depends_on: [db]
    command: -url=jdbc:postgresql://db:5432/blog_db -user=blog_admin -password=blog_password migrate
    volumes:
      - ./src/main/resources/db/migrations:/flyway/sql

  my-blog-backend:
    image: tomcat:9.0-jre11-slim
    depends_on: [db, flyway]
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./target/ROOT.war:/usr/local/tomcat/webapps/ROOT.war
      - ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml

  my-blog-front-app:
    build: ./frontend
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  blog_db:

